root: true

parser: '@typescript-eslint/parser'

parserOptions:
  sourceType: module
  ecmaVersion: latest
  project:
    - './tsconfig.json'
    - './tsconfig.eslint.json'
    - './cypress/tsconfig.json'

env:
  browser: true
  node: true
  es2021: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:cypress/recommended
  - plugin:jest-dom/recommended
  - plugin:testing-library/dom
  - prettier

plugins:
  - svelte3
  - '@typescript-eslint'

overrides:
  - files:
      - '*.svelte'
    processor: svelte3/svelte3
  - files:
      - 'cypress/integration/**/*.ts'
    rules:
      'testing-library/await-async-query': off
      'testing-library/prefer-screen-queries': off

settings:
  svelte3/typescript: true

rules:
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: ^_
      varsIgnorePattern: ^_

  no-console:
    - error
    - allow:
        - warn
        - error

  no-multiple-empty-lines:
    - error
    - max: 2
      maxEOF: 0

  operator-assignment:
    - error
    - always

  camelcase: error

  no-var: error

  prefer-const:
    - error
    - destructuring: all

  '@typescript-eslint/no-unnecessary-condition':
    - error
