name: Ensure code quality (testing, linting)
description: Performs linting with ESLint, unit testing with Jest and E2E testing with Cypress

inputs:
  supabaseUrl:
    description: 'Supabase Base URL'
    required: true
  supabaseKey:
    description: 'Supabase access key'
    required: true
  codecovToken:
    description: 'Codecov access key'
    required: true
  testUserPassword:
    description: 'The password of the Supabase user created for E2E tests'
    required: true
  applitoolsApiKey:
    description: 'The API key for Applitools to upload reports'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Use pnpm
      uses: pnpm/action-setup@10b4b0b462cfa1a30381c9d7c242194165a466ab
      with:
        version: 6.28.0

    - name: Cache 📦
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'pnpm'

    - name: Install dependencies 🔧
      shell: bash
      run: pnpm install

    - name: Check style and formatting 🧹
      shell: bash
      run: pnpm run lint

    - name: Run unit tests 🧪
      shell: bash
      run: pnpm run test:unit -- --ci --coverage
      env:
        VITE_SUPABASE_APP_URL: ${{ inputs.supabaseUrl }}
        VITE_SUPABASE_PUBLIC_ANON_KEY: ${{ inputs.supabaseKey }}

    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@53cfbc752e9c24b67aa0ada6f90cd0ea22c5f6d6
      with:
        token: ${{ inputs.codecovToken }}
        fail_ci_if_error: true

    - name: Run Cypress E2E tests 🧪
      uses: cypress-io/github-action@04ea5b90780c300adb0dc8cb01aff983956d7b9c
      env:
        VITE_SUPABASE_APP_URL: ${{ inputs.supabaseUrl }}
        VITE_SUPABASE_PUBLIC_ANON_KEY: ${{ inputs.supabaseKey }}
        TEST_USER_PASSWORD: ${{ inputs.testUserPassword }}
        APPLITOOLS_API_KEY: ${{ inputs.applitoolsApiKey }}
      with:
        build: pnpm run build
        start: pnpm run preview
        wait-on: 'http://localhost:3000'
        # we have already installed all dependencies above
        install: false
        cache-key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
