name: Ensure code quality (testing, linting)

inputs:
  supabaseUrl:
    description: 'Supabase Base URL'
    required: true
  supabaseKey:
    description: 'Supabase access key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Use pnpm
      uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.28.0

    - name: Cache 📦
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'pnpm'

    - name: Install dependencies 🔧
      shell: bash
      run: pnpm install

    - name: Check style and formatting 🧹
      shell: bash
      run: pnpm run lint

    - name: Run unit tests 🧪
      shell: bash
      run: pnpm run test:unit -- --ci

    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        fail_ci_if_error: true

    - name: Run Cypress E2E tests 🧪
      uses: cypress-io/github-action@v2
      env:
        VITE_SUPABASE_URL: ${{ inputs.supabaseUrl }}
        VITE_SUPABASE_KEY: ${{ inputs.supabaseKey }}
      with:
        build: pnpm run build
        start: pnpm run preview
        wait-on: 'http://localhost:3000'
        # we have already installed all dependencies above
        install: false
        cache-key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
