name: 'Reviewer lottery'
on:
  pull_request:
    types: [opened, ready_for_review, reopened]
    tags-ignore:
      - pair-programmed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: uesteibar/reviewer-lottery@v1
