name: 'Reviewer lottery'
on:
  pull_request:
    types: [labeled]

jobs:
  assign-reviewer:
    if: ${{ github.event.label.name != 'pair-programmed' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: uesteibar/reviewer-lottery@v1
